version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- npm install
build_script:
- npm run build
artifacts:
- path: dist\
  name: web-app
deploy:
- provider: WebDeploy
  server: https://hgv-butterfly.scm.azurewebsites.net:443/msdeploy.axd?site=hgv-butterfly
  website: hgv-butterfly
  username: $hgv-butterfly
  password:
    secure: 1cqbymVm2CozOdodmUrUe4BrPhBW0SiXl0cUFoS48mWwZXEOTFycwbVe1cavt/K+LBuBHGZ0/4LXq89zsEHpMQ==
  artifact: web-app
  remove_files: true
  app_offline: true